# Generated by Django 2.2.16 on 2023-01-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230113_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-author'], 'verbose_name': 'Лента автора', 'verbose_name_plural': 'Лента авторов'},
        ),
    ]
